### ISSUE TITLE
How to run 

### ISSUE THREAD

**Issue by alpha-beta-user** [quic/qbox#13]
This is a great work!

When I run the command cmake -B build;pushd build; make -j; popd, I do not know where the  executable program. Even though I have finished reading the readme. 

make help command in build directory show so many items, I do not know how they work.

can you tell me how to run the target prpgrama through config file like lua discribed in readme file. or mayebe a step_by_step to  run the qbox is better.

maybe I can change soc layout by adding a systemc module. 

thank you for your attention.

**Comment by tmarcero** [comment]
Hi @alpha-beta-user to build Qbox and run a customized ubuntu platform you just need to do this:

For aarch64:
```
cmake -Bbuild -DUBUNTU_ARCH=aarch64 -DLIBQEMU_TARGETS=aarch64
cd build
make -j
```
For riscv64:
```
cmake -Bbuild -DUBUNTU_ARCH=riscv64 -DLIBQEMU_TARGETS=riscv64
cd build
make -j
```
Then, in your build directory run:
```
make ubuntu
```
You will need to use these login info:
```
username: root
password: root
```

**Comment by alpha-beta-user** [comment]
thank you for your answer.

if I want to use my own systemc module,  what i need do.

and I want to know to test case. from braematal、uboot and os view.

I also want to know the where the excutable program is.

**Comment by tmarcero** [comment]
So if you want to run it by hand just do this section of the README:
https://github.com/quic/qbox?tab=readme-ov-file#run-it-by-hand

the line `./platforms/platforms-vp -l ../platforms/ubuntu/conf_aarch64.lua` allow to run the platform, so `platforms-vp` is your executable and `platforms/ubuntu/conf_aarch64.lua` is your configuration file where you can add your own systemc module in it.

About baremetal, you should turn on `has_el3` to `true` but we don't support that yet.
About the bootloader, and the binaries/images file, we load them thank to the systemC loader module:

```lua
    load={
        moduletype = "loader",
        initiator_socket = {bind = "&router.target_socket"};
        { bin_file=top().."fw/Artifacts/Image.bin", address=_KERNEL64_LOAD_ADDR };
        { bin_file=top().."fw/Artifacts/ubuntu.dtb", address=_DTB_LOAD_ADDR };
        { bin_file=top().."fw/Artifacts/image_ext4_initrd.img", address= _INITRD_LOAD_ADDR };
        { data=_bootloader_aarch64, address = INITIAL_DDR_SPACE};    
    };
```
