### ISSUE TITLE
Facing issues while running cmake -B build -DCPM_SOURCE_CACHE=`pwd`/Packages

### ISSUE THREAD

**Issue by Aabhash23** [quic/qbox#8]
im facing the below issue while using this command

  CMakeLists.txt:217 (gs_addpackage)
This warning is for project developers.  Use -Wno-dev to suppress it.

[ 11%] Creating directories for 'libqemu-populate'
[ 22%] Performing download step (git clone) for 'libqemu-populate'
Cloning into 'd2ea49f3eca205bfa95b36b8e0713d4ce20d1ae6'...
fatal: invalid reference: libqemu-v8.2-v0.1.14
CMake Error at /home/kpit/Desktop/qbox/build/_deps/libqemu-subbuild/libqemu-populate-prefix/tmp/libqemu-populate-gitclone.cmake:61 (message):
  Failed to checkout tag: 'libqemu-v8.2-v0.1.14'

make[2]: *** [CMakeFiles/libqemu-populate.dir/build.make:102: libqemu-populate-prefix/src/libqemu-populate-stamp/libqemu-populate-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/libqemu-populate.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

CMake Error at /snap/cmake/1409/share/cmake-3.30/Modules/FetchContent.cmake:1918 (message):
  Build step for libqemu failed: 2
Call Stack (most recent call first):
  /snap/cmake/1409/share/cmake-3.30/Modules/FetchContent.cmake:1609 (__FetchContent_populateSubbuild)
  /snap/cmake/1409/share/cmake-3.30/Modules/FetchContent.cmake:2145:EVAL:2 (__FetchContent_doPopulation)
  /snap/cmake/1409/share/cmake-3.30/Modules/FetchContent.cmake:2145 (cmake_language)
  /snap/cmake/1409/share/cmake-3.30/Modules/FetchContent.cmake:1978:EVAL:1 (__FetchContent_Populate)
  /snap/cmake/1409/share/cmake-3.30/Modules/FetchContent.cmake:1978 (cmake_language)
  build/_deps/cpm-cmake-src/cmake/CPM.cmake:738 (FetchContent_Populate)
  build/_deps/cpm-cmake-src/cmake/CPM.cmake:595 (cpm_fetch_package)
  build/_deps/cpm-cmake-src/cmake/CPM.cmake:493 (CPMAddPackage)
  cmake/boilerplate.cmake:332 (CPMAddPackage)
  CMakeLists.txt:217 (gs_addpackage)

**Comment by alwalidsalama** [comment]
Hello @Aabhash23, we expect libqemu-v8.2-v0.1.14 to be added soon!

For now please go for [qbox v3.0.1](https://github.com/quic/qbox/tree/v3.0.1) and [libqemu v8.2-v0.1.4](https://github.com/quic/qemu/tree/libqemu-v8.2-v0.1.4).

Simply:
git clone https://github.com/quic/qbox.git
git checkout v3.0.1

modify https://github.com/quic/qbox/blob/v3.0.1/package-lock.cmake#L11  to be GIT_REPOSITORY ${GREENSOCS_GIT}qemu.git
